#!/usr/bin/env node
/**
 * MindReply Quick Start
 * Interactive deployment wizard
 */

const fs = require('fs');
const readline = require('readline');
const { execSync } = require('child_process');

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const ask = (q) => new Promise(r => rl.question(q, r));

  console.log(`
╔════════════════════════════════════════════════════════════╗
║                                                            ║
║              🚀 MindReply Live Deployment                 ║
║                                                            ║
║        AI Agent Payments + RWA Acquisition Platform       ║
║                                                            ║
╚════════════════════════════════════════════════════════════╝
  `);

  // Gather Stripe credentials
  console.log('\n💳 STRIPE CONFIGURATION\n');
  console.log('Get these from https://dashboard.stripe.com/apikeys\n');

  const stripeSecretKey = await ask('Stripe Secret Key (sk_live_ or sk_test_): ');
  const stripePublishableKey = await ask('Stripe Publishable Key (pk_live_ or pk_test_): ');
  const stripeWebhookSecret = await ask('Stripe Webhook Secret (whsec_): ');

  // GitHub setup
  console.log('\n🐙 GITHUB CONFIGURATION\n');
  const githubUser = await ask('GitHub username: ');
  const repoName = await ask('Repository name (default: mind-reply-core): ') || 'mind-reply-core';

  // Deployment choice
  console.log('\n☁️  DEPLOYMENT CHOICE\n');
  console.log('Options:');
  console.log('  1) Local (docker-compose on this machine)');
  console.log('  2) Self-hosted (Docker Swarm)');
  console.log('  3) Cloud (DigitalOcean, AWS, etc.)');
  const deployChoice = await ask('\nChoice (1/2/3, default 1): ') || '1';

  const deploymentTypes = { '1': 'local', '2': 'self-hosted', '3': 'cloud' };
  const deploymentType = deploymentTypes[deployChoice] || 'local';

  let domain = 'localhost';
  if (deploymentType !== 'local') {
    domain = await ask('Production domain (e.g., mindreply.com): ') || 'localhost';
  }

  // Create .env file
  console.log('\n📝 Creating .env file...');
  const envContent = `# Production Environment (Generated by Quick Start)
NODE_ENV=production
NEXT_TELEMETRY_DISABLED=1

# Stripe Machine Payments
STRIPE_SECRET_KEY=${stripeSecretKey}
STRIPE_PUBLISHABLE_KEY=${stripePublishableKey}
STRIPE_WEBHOOK_SECRET=${stripeWebhookSecret}

# RWA Bridge
LEGAL_ENTITY_API_URL=https://api.otoco.io/v1
AGENT_WALLET_ADDRESS=0x321...AI_AGENT
AGENT_SESSION_KEY=0x_scoped_session_token

# Supabase (Database)
SUPABASE_URL=https://aziwdgndohdgnwztpwdi.supabase.co
SUPABASE_SECRET_KEY=sb_secret_REPLACE_IN_SECRET_MANAGER
SUPABASE_DATABASE_URL=postgresql://postgres:PASSWORD@db.supabase.co:5432/postgres
`;

  fs.writeFileSync('.env', envContent);
  console.log('✓ .env file created\n');

  // Push to GitHub
  console.log('📍 Pushing to GitHub...');
  try {
    execSync(`git remote set-url origin https://github.com/${githubUser}/${repoName}.git`);
    execSync('git add .');
    execSync('git commit -m "deployment: Live deployment initiated" || true');
    execSync('git branch -M main');
    execSync('git push -u origin main');
    console.log('✓ Pushed to GitHub\n');
  } catch (e) {
    console.log('⚠ GitHub push failed - make sure the repo exists\n');
  }

  // Build Docker images
  console.log('🐳 Building Docker images...');
  console.log('This may take 5-10 minutes...\n');

  try {
    console.log('[1/2] Building RWA Bridge...');
    execSync('docker build -f Dockerfile -t rwa-bridge:latest .', { stdio: 'inherit' });
    console.log('\n[2/2] Building Next.js Frontend...');
    execSync('docker build -f apps/web-replycontrol/Dockerfile -t web-replycontrol:latest .', { stdio: 'inherit' });
    console.log('\n✓ Docker images built\n');
  } catch (e) {
    console.error('❌ Docker build failed');
    process.exit(1);
  }

  // Deploy
  console.log('🚀 Deploying...\n');

  if (deploymentType === 'local') {
    console.log('Starting services locally...');
    try {
      execSync('docker compose down 2>/dev/null || true', { stdio: 'ignore' });
      execSync('docker compose up -d');
      console.log('\n✓ Services started\n');

      console.log('Waiting for services to be ready...');
      for (let i = 0; i < 20; i++) {
        try {
          execSync('curl -sf http://localhost:3000/api/health > /dev/null 2>&1');
          console.log('\n✓ Frontend is healthy');
          break;
        } catch (e) {
          process.stdout.write('.');
          require('child_process').execSync('sleep 1');
        }
      }
    } catch (e) {
      console.error('❌ Deployment failed');
      process.exit(1);
    }
  } else if (deploymentType === 'self-hosted') {
    console.log('Deploy with: docker compose -f docker-compose.prod.yml up -d');
  } else {
    console.log('See LIVE_DEPLOYMENT.md for cloud deployment guides');
  }

  // Summary
  console.log(`
╔════════════════════════════════════════════════════════════╗
║                                                            ║
║                   ✅ DEPLOYMENT COMPLETE                  ║
║                                                            ║
╚════════════════════════════════════════════════════════════╝

📍 ACCESS YOUR PLATFORM:

  Frontend:  http://${domain === 'localhost' ? 'localhost' : domain}:3000
  API:       http://${domain === 'localhost' ? 'localhost' : domain}:3000/api
  RWA:       http://${domain === 'localhost' ? 'localhost' : domain}:8000
  Health:    http://${domain === 'localhost' ? 'localhost' : domain}:3000/api/health

💳 NEXT STEPS:

  1. Add GitHub Secrets:
     Go to: https://github.com/${githubUser}/${repoName}/settings/secrets/actions
     Add: STRIPE_SECRET_KEY, STRIPE_PUBLISHABLE_KEY, STRIPE_WEBHOOK_SECRET

  2. Configure Stripe Webhook:
     Go to: https://dashboard.stripe.com/webhooks
     Update URL to: https://${domain}/api/payments/webhook

  3. Test Payment:
     curl -X POST http://${domain === 'localhost' ? 'localhost' : domain}:3000/api/payments \\
       -H "Content-Type: application/json" \\
       -d '{"agent_id":"test","service_type":"rwa_bridge","amount_cents":50,"currency":"usd","payment_method":"spt"}'

  4. Monitor:
     Logs: docker compose logs -f
     Stripe: https://dashboard.stripe.com/payments

📚 DOCUMENTATION:

  Full Guide: MASTER_EXECUTION_GUIDE.md
  Deployment: LIVE_DEPLOYMENT.md
  Stripe:     STRIPE_SETUP.md
  API Ref:    README_NEW.md

🎉 You're live! Ready to accept agent payments.
  `);

  rl.close();
}

main().catch(console.error);
