"use client";
import Link from "next/link";
import "./dashboard.css";
const nav=[["Desk","/dashboard"],["Chat","/dashboard/chat"],["Today","/dashboard/today"],["Growth","/dashboard/growth"],["Approvals","/dashboard/approvals"],["ReplyControl","/dashboard/replycontrol"],["Proof","/dashboard/proof"],["Settings","/dashboard/settings"]];
const moves=[["Money move","Follow up with the warmest open opportunity","Draft"],["Client move","Turn the last unanswered question into a clear next step","Open"],["Proof move","Save evidence from the latest route check","Save proof"],["Risk move","Review one blocked outbound action","Check"],["Visibility move","Prepare one useful public insight","Draft"]];
export function DashboardShell({title="Private Desk",children}:{title?:string;children?:React.ReactNode}){return <main className="desk"><aside className="desk-nav"><div className="brand"><span className="brand-mark">M</span><div><strong>MindReply</strong><small>Private Desk</small></div></div><nav>{nav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><div className="guard"><b>Owner gate</b><span>External actions require approval.</span></div></aside><section className="desk-main"><header className="topbar"><div><small>PRIVATE / OWNER CONTROL</small><h1>{title}</h1></div><div className="demo">DEMO ONLY · CONNECT STORAGE FOR LIVE DATA</div></header>{children}</section></main>}
export function MoveCard({kind,text,action}:{kind:string;text:string;action:string}){return <article className="card move"><span className="eyebrow">{kind}</span><p>{text}</p><div className="actions"><button onClick={()=>alert(`${action}: owner review required`)}>{action}</button><button className="quiet">Block</button></div></article>}
export function DeskHome(){return <><section className="hero-grid"><article className="card best"><span className="eyebrow">TODAY'S BEST MOVE</span><h2>Recover one valuable conversation before creating another.</h2><p>Three warm threads are ready for a human-approved follow-up.</p><div className="actions"><button>Open</button><button className="quiet">Check</button></div></article><article className="card score"><span className="eyebrow">CONTROL</span><strong>7</strong><span>items awaiting owner decision</span><hr/><span>0 external messages sent</span></article></section><section className="section"><div className="section-head"><h2>20 Useful Moves</h2><span>5 priority · 15 queued</span></div><div className="move-grid">{moves.map(([k,t,a])=><MoveCard key={k} kind={k} text={t} action={a}/>)}</div></section><section className="section"><div className="section-head"><h2>Approval queue</h2><span>Human decision boundary</span></div><div className="queue"><div><b>ReplyControl follow-up</b><span>Draft · no recipient contacted</span></div><div className="actions"><button>Approve</button><button className="quiet">Edit</button><button className="quiet">Block</button></div></div></section></>}
export function PagePanel({heading,description,children}:{heading:string;description:string;children?:React.ReactNode}){return <section className="section"><div className="panel-intro"><span className="eyebrow">PRIVATE DESK</span><h2>{heading}</h2><p>{description}</p></div>{children||<div className="card empty">DEMO ONLY — this surface is wired for the next connector step.</div>}</section>}
